[package]
name = "rvoip-transaction-core"
# 🎯 INHERIT VERSION AND METADATA FROM WORKSPACE!
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

# Crate-specific description
description = "SIP transaction layer for the rvoip stack"

# ✨ INHERIT LINTS FROM WORKSPACE
[lints]
workspace = true

[dependencies]
# Our own crates
rvoip-sip-core = { path = "../sip-core", version = "0.1.4" }
rvoip-sip-transport = { path = "../sip-transport", features = ["udp", "tcp", "tls", "ws"], version = "0.1.4" }

# Async runtime
tokio = { version = "1.28.2", features = ["full"] }
async-trait = "0.1.60"
futures = "0.3"
pin-project = "1.0"

# Error handling
thiserror = "1.0.40"

# Utilities
uuid = { version = "1.0", features = ["v4"] }

# Logging
tracing = "0.1.37"

# Added from the code block
rand = "0.8"
lazy_static = "1.4.0"

[dev-dependencies]
serial_test = "3.2.0"
tokio = { workspace = true, features = ["full", "test-util"] }
tracing-subscriber = { workspace = true } 
