[package]
name = "rvoip-call-engine"
version = "0.1.0"
edition = "2021"
description = "Call routing and business logic for the rvoip stack"
license = "MIT OR Apache-2.0"

# Silence all Rust warnings
[lints.rust]
warnings = "allow"

[dependencies]
# Our own crates
rvoip-sip-core = { path = "../sip-core" }
rvoip-transaction-core = { path = "../transaction-core" }
rvoip-session-core = { path = "../session-core" }
rvoip-media-core = { path = "../media-core" }
rvoip-rtp-core = { path = "../rtp-core" }
rvoip-sip-transport = { path = "../sip-transport" }

# Database
limbo = "0.0.20"

# Async runtime
tokio = { workspace = true, features = ["full"] }
async-trait = "0.1"

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# Utilities
bytes = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Infrastructure
infra-common = { path = "../infra-common", features = ["no-global-allocator"] }

# Collections
dashmap = "5.5"
parking_lot = "0.12"

[dev-dependencies]
# Testing
tokio-test = "0.4"
serial_test = "3.1"

# Benchmarking
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }

# For examples
clap = { version = "4.5", features = ["derive"] }
rvoip-client-core = { path = "../client-core" }

[[bench]]
name = "call_center_benchmarks"
harness = false

[[example]]
name = "phase0_basic_call_flow"
path = "examples/phase0_basic_call_flow.rs"

[[example]]
name = "phase2_call_routing_demo"
path = "examples/phase2_call_routing_demo.rs"

[[example]]
name = "call_center_with_database"
path = "examples/call_center_with_database.rs"

[[example]]
name = "register_demo_server"
path = "examples/register_demo/server.rs"

[[example]]
name = "register_demo_client"
path = "examples/register_demo/client.rs"

[[example]]
name = "e2e_test_server"
path = "examples/e2e_test/server/basic_call_center_server.rs"

[[example]]
name = "e2e_test_agent"
path = "examples/e2e_test/agent/agent_client.rs" 