[package]
name = "rvoip-call-engine"
version = "0.1.0"
edition = "2021"
description = "Call routing and business logic for the rvoip stack"
license = "MIT OR Apache-2.0"

# Silence all Rust warnings
[lints.rust]
warnings = "allow"

[dependencies]
# Our own crates
rvoip-sip-core = { path = "../sip-core" }
rvoip-transaction-core = { path = "../transaction-core" }
rvoip-session-core = { path = "../session-core" }
rvoip-media-core = { path = "../media-core" }
rvoip-rtp-core = { path = "../rtp-core" }
rvoip-sip-transport = { path = "../sip-transport" }

# Database
limbo = "0.0.20"

# Async runtime
tokio = { workspace = true, features = ["full"] }
async-trait = "0.1"

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# Utilities
bytes = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Infrastructure
infra-common = { path = "../infra-common", features = ["no-global-allocator"] }

# Collections
dashmap = "5.5"
parking_lot = "0.12"

[dev-dependencies]
# Testing
tokio-test = "0.4"

# Benchmarking
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }

[[bench]]
name = "call_center_benchmarks"
harness = false 