[package]
name = "rvoip-call-engine"
version = "0.1.0"
edition = "2021"
description = "Call routing and business logic for the rvoip stack"
license = "MIT OR Apache-2.0"

# Silence all Rust warnings
[lints.rust]
warnings = "allow"

[dependencies]
# Workspace crates
rvoip-sip-transport = { path = "../sip-transport" }
rvoip-sip-core = { path = "../sip-core" }
# Our own crates - following client-core pattern
rvoip-session-core = { path = "../session-core" }
# Infrastructure - shared types
infra-common = { path = "../infra-common", features = ["no-global-allocator"] }

# Database - Modern async approach with sqlx
# Replace rusqlite/r2d2 with sqlx for true async support
sqlx = { version = "0.7", features = [
    "runtime-tokio-rustls",
    "sqlite", 
    "chrono", 
    "uuid",
    "migrate",
    "macros"
] }

# Web framework
axum = "0.7"

# Async runtime
tokio = { workspace = true, features = ["full"] }
async-trait = "0.1"

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# Utilities
bytes = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Collections
dashmap = "5.5"
parking_lot = "0.12"

# For examples
clap = { version = "4.5", features = ["derive"] }
rvoip-client-core = { path = "../client-core" }

[dev-dependencies]
# Testing
tokio-test = "0.4"
serial_test = "3.1"

# Benchmarking
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }

[[example]]
name = "e2e_test_server"
path = "examples/e2e_test/server/basic_call_center_server.rs"

[[example]]
name = "e2e_test_agent"
path = "examples/e2e_test/agent/agent_client.rs" 
