[package]
name = "rvoip-sip-transport"
version = "0.1.0"
edition = "2021"
description = "SIP transport layer implementation for the rvoip stack"
license = "MIT OR Apache-2.0"

# Silence all Rust warnings
[lints.rust]
warnings = "allow"

[dependencies]
# Our own crates
rvoip-sip-core = { path = "../sip-core" }

# Async runtime
tokio = { workspace = true, features = ["net", "sync", "io-util", "time"] }
async-trait = "0.1"

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# Serialization
bytes = { workspace = true }

# Logging
tracing = { workspace = true }

# TLS support
tokio-rustls = { version = "0.24", optional = true }
rustls = { version = "0.21", optional = true }
rustls-pemfile = { version = "1.0", optional = true }

# Add futures-util dependency
futures-util = "0.3"

[features]
default = ["udp", "tls"]
udp = []
tls = ["dep:tokio-rustls", "dep:rustls", "dep:rustls-pemfile"]
tcp = []
ws = []

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
tracing-subscriber = { workspace = true } 