[package]
name = "rvoip-sip-transport"
version = "0.1.0"
edition = "2021"
description = "SIP transport layer implementation for the rvoip stack"
license = "MIT OR Apache-2.0"

[dependencies]
# Our own crates
rvoip-sip-core = { path = "../sip-core" }

# Async runtime
tokio = { workspace = true, features = ["net", "sync", "io-util", "time"] }
async-trait = "0.1"

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# Serialization
bytes = { workspace = true }

# Logging
tracing = { workspace = true }

# TLS support
tokio-rustls = "0.24"
rustls = "0.21"
rustls-pemfile = "1.0"

[features]
default = ["udp", "tls"]
udp = []
tls = ["tokio-rustls", "rustls", "rustls-pemfile"]
tcp = []
ws = []

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
tracing-subscriber = { workspace = true } 