[package]
name = "call-center-demo"
version = "0.1.0"
edition = "2021"
description = "Call center demo with real audio streaming using call-engine and client-core"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "agent"
path = "src/agent.rs"

[[bin]]
name = "customer"
path = "src/customer.rs"

[dependencies]
# Core RVOIP umbrella crate
rvoip = "0.1.14"

# Runtime and async
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"

# CLI and utilities
clap = { version = "4.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4"] }
anyhow = "1.0"
serde_json = "1.0"

[workspace] 