[package]
name = "sip-client-demo"
version = "0.1.0"
edition = "2021"
description = "Demo application for the RVOIP SIP client library"
publish = false

# Turn off specific warnings
[lints.rust]
unused_imports = "allow"

[dependencies]
# Use our SIP client library with default features (including ICE)
rvoip-sip-client = { path = "../../crates/sip-client" }

# Async runtime and utilities
tokio = { version = "1.29", features = ["full"] }
anyhow = "1.0"
clap = { version = "4.3", features = ["derive", "env"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3"

[[bin]]
name = "caller"
path = "src/caller.rs"

[[bin]]
name = "receiver"
path = "src/receiver.rs"

[[bin]]
name = "call_history"
path = "src/call_history.rs" 