[package]
name = "sip-test-client"
version = "0.1.0"
edition = "2021"
description = "A test client for the RVOIP SIP stack"
publish = false

# Silence all Rust warnings
[lints.rust]
warnings = "allow"

[dependencies]
# Core crates
rvoip-sip-core = { path = "../../crates/sip-core" }
rvoip-sip-transport = { path = "../../crates/sip-transport" }
rvoip-transaction-core = { path = "../../crates/transaction-core" }
rvoip-session-core = { path = "../../crates/session-core" }
# Add RTP and media support
rvoip-rtp-core = { path = "../../crates/rtp-core" }
rvoip-media-core = { path = "../../crates/media-core" }
# New SIP client library
rvoip-sip-client = { path = "../../crates/sip-client" }

# Async runtime and utilities
tokio = { version = "1.29", features = ["full"] }
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.4", features = ["v4"] }
async-trait = "0.1"
md5 = "0.7"

[dependencies.bytes]
version = "1.4" 