[package]
name = "g729a-new"
version = "0.1.0"
edition = "2021"

[dependencies]

[[test]]
name = "lsp"
path = "tests/lsp/rust_test.rs"

[[test]]
name = "lpc"
path = "tests/lpc/rust_test.rs"

[[test]]
name = "pre_proc"
path = "tests/pre_proc/rust_test.rs"

[[test]]
name = "discrete_comparison"
path = "tests/discrete_comparison/test_all.rs"

[[test]]
name = "rust_test"
path = "tests/rust_test.rs"

[[test]]
name = "test_mult"
path = "tests/test_mult.rs"

[[test]]
name = "lsp_quantizer"
path = "tests/lsp_quantizer/rust_test.rs"

[[test]]
name = "rust_test_compat"
path = "tests/lsp_quantizer/rust_test_compat.rs"

[[test]]
name = "rust_ma_state_test"
path = "tests/lsp_quantizer/rust_ma_state_test.rs"

[workspace]
