[package]
name = "g729a-new"
version = "0.1.0"
edition = "2021"

[dependencies]

[[test]]
name = "discrete_comparison"
path = "tests/discrete_comparison/rust_test.rs"

[[test]]
name = "pre_proc"
path = "tests/pre_proc/rust_test.rs"

[[test]]
name = "lpc"
path = "tests/lpc/rust_test.rs"

[workspace]
