 [package]
name = "rtp-g711"
version = "0.1.0"
edition = "2021"
description = "Example demonstrating G.711 codec over RTP"

# Use workspace dependencies
[dependencies]
# Core crates
rvoip-rtp-core = { path = "../../crates/rtp-core" }
rvoip-media-core = { path = "../../crates/media-core" }

# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Bytes handling
bytes = "1.5"

# Silence all Rust warnings
[lints.rust]
warnings = "allow"

[[bin]]
name = "rtp-g711"
path = "src/main.rs" 