//! H7.5: in-process TLS termination for WHIP (HTTPS) and WS (WSS).
//!
//! Self-signed cert generated by `rcgen` at runtime — no fixture cert files.

#![cfg(all(
    feature = "tls-rustls",
    feature = "signaling-whip",
    feature = "signaling-ws"
))]

use std::sync::Arc;
use std::time::Duration;

use futures::{SinkExt, StreamExt};
use rcgen::generate_simple_self_signed;
use rvoip_webrtc::peer::{PeerRole, RvoipPeerConnection};
use rvoip_webrtc::tls::TlsConfig;
use rvoip_webrtc::{WebRtcConfig, WebRtcServerBuilder};

fn self_signed_pem() -> (Vec<u8>, Vec<u8>) {
    let cert =
        generate_simple_self_signed(vec!["localhost".into(), "127.0.0.1".into()]).expect("cert");
    let cert_pem = cert.cert.pem().into_bytes();
    let key_pem = cert.signing_key.serialize_pem().into_bytes();
    (cert_pem, key_pem)
}

async fn fresh_offer() -> String {
    let _ = rustls::crypto::ring::default_provider().install_default();
    let peer = Arc::new(
        RvoipPeerConnection::new(&WebRtcConfig::loopback(), PeerRole::Offerer)
            .await
            .expect("offerer"),
    );
    peer.add_local_audio_track().await.expect("audio");
    peer.create_offer_and_gather().await.expect("offer")
}

#[tokio::test]
async fn whips_post_returns_201_over_tls() {
    let _ = rustls::crypto::ring::default_provider().install_default();
    let (cert_pem, key_pem) = self_signed_pem();
    let tls = TlsConfig::from_pem_bytes(&cert_pem, &key_pem)
        .await
        .expect("tls config");

    let server = WebRtcServerBuilder::new(WebRtcConfig::loopback())
        .with_whips("127.0.0.1:0", tls)
        .build()
        .await
        .expect("server");
    let addr = server.whips_addr().expect("whips addr");

    // reqwest with danger_accept_invalid_certs — self-signed.
    let http = reqwest::Client::builder()
        .danger_accept_invalid_certs(true)
        .timeout(Duration::from_secs(10))
        .build()
        .expect("http");
    let offer = fresh_offer().await;
    let resp = http
        .post(format!("https://{addr}/whip/tls-test"))
        .header("content-type", "application/sdp")
        .body(offer)
        .send()
        .await
        .expect("post");
    assert_eq!(resp.status(), reqwest::StatusCode::CREATED);
    assert!(resp.headers().get("etag").is_some());

    // Healthz over TLS.
    let h = http
        .get(format!("https://{addr}/healthz"))
        .send()
        .await
        .expect("healthz");
    assert_eq!(h.status(), reqwest::StatusCode::OK);
    assert_eq!(h.text().await.unwrap(), "ok");

    server.shutdown().await;
}

#[tokio::test]
async fn wss_offer_round_trip_completes() {
    let _ = rustls::crypto::ring::default_provider().install_default();
    let (cert_pem, key_pem) = self_signed_pem();
    let tls = TlsConfig::from_pem_bytes(&cert_pem, &key_pem)
        .await
        .expect("tls config");

    let server = WebRtcServerBuilder::new(WebRtcConfig::loopback())
        .with_wss("127.0.0.1:0", tls)
        .build()
        .await
        .expect("server");
    let addr = server.wss_addr().expect("wss addr");

    // Build a tokio-tungstenite client with custom rustls connector that
    // accepts the self-signed cert.
    let mut roots = rustls::RootCertStore::empty();
    // Skip cert verification entirely (self-signed test).
    let config = rustls::ClientConfig::builder()
        .dangerous()
        .with_custom_certificate_verifier(Arc::new(InsecureVerifier))
        .with_no_client_auth();
    let connector = tokio_tungstenite::Connector::Rustls(Arc::new(config));
    let _ = roots; // suppress unused

    let url = format!("wss://{addr}");
    let req = tokio_tungstenite::tungstenite::client::IntoClientRequest::into_client_request(&*url)
        .expect("request");
    let (mut ws, _resp) =
        tokio_tungstenite::connect_async_tls_with_config(req, None, false, Some(connector))
            .await
            .expect("wss connect");

    // Send an offer and expect an answer.
    let offer = fresh_offer().await;
    let msg = serde_json::json!({
        "type": "offer",
        "sdp": offer,
        "connection_id": "",
        "candidate": "",
    });
    ws.send(tokio_tungstenite::tungstenite::Message::Text(
        msg.to_string().into(),
    ))
    .await
    .expect("send offer");

    let reply = tokio::time::timeout(Duration::from_secs(10), ws.next())
        .await
        .expect("timeout")
        .expect("none")
        .expect("err");
    let text = reply.into_text().expect("text");
    let parsed: serde_json::Value = serde_json::from_str(&text).expect("json");
    assert_eq!(parsed["type"], "answer");
    assert!(parsed["sdp"].as_str().expect("sdp").contains("m=audio"));

    server.shutdown().await;
}

#[derive(Debug)]
struct InsecureVerifier;

impl rustls::client::danger::ServerCertVerifier for InsecureVerifier {
    fn verify_server_cert(
        &self,
        _end_entity: &rustls::pki_types::CertificateDer<'_>,
        _intermediates: &[rustls::pki_types::CertificateDer<'_>],
        _server_name: &rustls::pki_types::ServerName<'_>,
        _ocsp_response: &[u8],
        _now: rustls::pki_types::UnixTime,
    ) -> Result<rustls::client::danger::ServerCertVerified, rustls::Error> {
        Ok(rustls::client::danger::ServerCertVerified::assertion())
    }
    fn verify_tls12_signature(
        &self,
        _message: &[u8],
        _cert: &rustls::pki_types::CertificateDer<'_>,
        _dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        Ok(rustls::client::danger::HandshakeSignatureValid::assertion())
    }
    fn verify_tls13_signature(
        &self,
        _message: &[u8],
        _cert: &rustls::pki_types::CertificateDer<'_>,
        _dss: &rustls::DigitallySignedStruct,
    ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
        Ok(rustls::client::danger::HandshakeSignatureValid::assertion())
    }
    fn supported_verify_schemes(&self) -> Vec<rustls::SignatureScheme> {
        vec![
            rustls::SignatureScheme::RSA_PKCS1_SHA256,
            rustls::SignatureScheme::ECDSA_NISTP256_SHA256,
            rustls::SignatureScheme::ED25519,
        ]
    }
}
