[package]
name = "rvoip-presets"
version = "0.1.0"
edition = "2021"
description = "Pre-configured patterns and use-case templates for RVOIP platform"
authors = ["RVOIP Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rvoip/rvoip"
keywords = ["voip", "sip", "rtp", "presets", "templates"]
categories = ["network-programming", "multimedia", "config"]

[dependencies]
# High-level RVOIP crates
rvoip-simple = { path = "../rvoip-simple", version = "0.1.0" }

# Core RVOIP crates (for advanced configurations)
rvoip-sip-core = { path = "../sip-core", version = "0.1.0" }
rvoip-call-engine = { path = "../call-engine", version = "0.1.0" }
rvoip-rtp-core = { path = "../rtp-core", version = "0.1.0" }
rvoip-api-server = { path = "../api-server", version = "0.1.0" }
rvoip-session-core = { path = "../session-core", version = "0.1.0" }
rvoip-infra-common = { path = "../infra-common", version = "0.1.0" }

# Async runtime and utilities
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "sync", "net", "time", "macros"] }
tracing = "0.1.40"
thiserror = "1.0.56"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.6.1", features = ["v4"] }

[dev-dependencies]
tokio-test = "0.4"
tracing-subscriber = "0.3"

[features]
default = ["all-presets"]
all-presets = [
    "enterprise-pbx", "cloud-pbx", "mobile-app", "webrtc-platform", 
    "contact-center", "cpaas-platform", "healthcare", "financial"
]

# Use case specific features
enterprise-pbx = []
cloud-pbx = []
mobile-app = []
webrtc-platform = []
contact-center = []
cpaas-platform = []
healthcare = []
financial = []

[[example]]
name = "enterprise_pbx"
path = "examples/enterprise_pbx.rs"

[[example]]
name = "mobile_voip_app"
path = "examples/mobile_voip_app.rs"

[[example]]
name = "webrtc_platform"
path = "examples/webrtc_platform.rs" 