[package]
name = "rvoip-sip-core"
# 🎯 INHERIT VERSION AND METADATA FROM WORKSPACE!
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

# Crate-specific description
description = "SIP protocol implementation for the rvoip stack"

# ✨ INHERIT LINTS FROM WORKSPACE
[lints]
workspace = true

# Features
[features]
default = ["sdp"]  # Include sdp in the default features
lenient_parsing = []  # More lenient parsing for torture tests
sdp = []  # Session Description Protocol support

[dependencies]
# Workspace dependencies
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
bytes.workspace = true
uuid.workspace = true
tracing.workspace = true
chrono.workspace = true
rand.workspace = true
log.workspace = true

# Crate-specific dependencies not in workspace
serde_bytes.workspace = true
base64.workspace = true
nom.workspace = true
ordered-float.workspace = true

[dev-dependencies]
proptest.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
async-trait.workspace = true

# Integration tests configuration
[[test]]
name = "torture_tests"
path = "tests/rfc_compliance/torture_test.rs"
required-features = ["lenient_parsing"]

[[test]]
name = "parser"
path = "tests/parser_tests.rs"
