//! Heavy validation for SIP messages generated by this stack.
//!
//! This module is intentionally gated behind tests or the
//! `generated-validation` feature. It serializes and strict-parses generated
//! messages to catch builder regressions, while production send paths use the
//! cheaper wire validator.

use std::collections::HashMap;

use crate::parser::message::{parse_message_with_mode, ParseMode};
use crate::types::headers::HeaderAccess;
use crate::types::{
    headers::{HeaderName, TypedHeader},
    sip_request::Request,
    sip_response::Response,
    Message,
};
use crate::validation::{validate_wire_request, validate_wire_response};
use crate::{Error, Result};

fn validation_error(message: impl Into<String>) -> Error {
    Error::ValidationError(message.into())
}

/// Validate a generated SIP message and return its strict-parsed copy.
pub fn validate_generated_message(message: &Message) -> Result<Message> {
    match message {
        Message::Request(request) => validate_generated_request(request).map(Message::Request),
        Message::Response(response) => validate_generated_response(response).map(Message::Response),
    }
}

/// Validate a generated SIP request and return its strict-parsed copy.
pub fn validate_generated_request(request: &Request) -> Result<Request> {
    validate_wire_request(request)?;
    validate_duplicate_singletons(
        &request.headers,
        &[
            HeaderName::From,
            HeaderName::To,
            HeaderName::CallId,
            HeaderName::CSeq,
            HeaderName::MaxForwards,
            HeaderName::ContentLength,
            HeaderName::ContentType,
            HeaderName::Expires,
            HeaderName::Event,
            HeaderName::SubscriptionState,
            HeaderName::RAck,
        ],
        "request",
    )?;

    let parsed = strict_roundtrip(Message::Request(request.clone()))?;
    let Message::Request(parsed_request) = parsed else {
        return Err(validation_error(
            "generated request strict-parsed as response",
        ));
    };

    validate_wire_request(&parsed_request)?;
    assert_request_semantics_survived(request, &parsed_request)?;
    Ok(parsed_request)
}

/// Validate a generated SIP response and return its strict-parsed copy.
pub fn validate_generated_response(response: &Response) -> Result<Response> {
    validate_wire_response(response)?;
    validate_duplicate_singletons(
        &response.headers,
        &[
            HeaderName::From,
            HeaderName::To,
            HeaderName::CallId,
            HeaderName::CSeq,
            HeaderName::ContentLength,
            HeaderName::ContentType,
            HeaderName::Expires,
            HeaderName::MinExpires,
            HeaderName::RSeq,
        ],
        "response",
    )?;

    let parsed = strict_roundtrip(Message::Response(response.clone()))?;
    let Message::Response(parsed_response) = parsed else {
        return Err(validation_error(
            "generated response strict-parsed as request",
        ));
    };

    validate_wire_response(&parsed_response)?;
    assert_response_semantics_survived(response, &parsed_response)?;
    Ok(parsed_response)
}

fn strict_roundtrip(message: Message) -> Result<Message> {
    let bytes = message.to_bytes();
    let separator = validate_serialized_framing(&bytes)?;
    let (headers, body) = bytes.split_at(separator);
    let body = &body[4..];
    validate_serialized_content_length(headers, body.len())?;

    parse_message_with_mode(&bytes, ParseMode::Strict)
}

fn validate_serialized_framing(bytes: &[u8]) -> Result<usize> {
    let separators = bytes
        .windows(4)
        .enumerate()
        .filter_map(|(idx, window)| (window == b"\r\n\r\n").then_some(idx))
        .collect::<Vec<_>>();

    let Some(first_separator) = separators.first().copied() else {
        return Err(validation_error(
            "generated SIP message missing CRLF header/body separator",
        ));
    };

    if separators.len() != 1 {
        return Err(validation_error(format!(
            "generated SIP message has {} CRLF header/body separators",
            separators.len()
        )));
    }

    let header_block = &bytes[..first_separator];
    for (idx, byte) in header_block.iter().enumerate() {
        if *byte == b'\n' && (idx == 0 || header_block[idx - 1] != b'\r') {
            return Err(validation_error(
                "generated SIP header block contains LF without CRLF",
            ));
        }
    }

    Ok(first_separator)
}

fn validate_serialized_content_length(header_block: &[u8], body_len: usize) -> Result<()> {
    let header_text = std::str::from_utf8(header_block)
        .map_err(|_| validation_error("generated SIP headers are not UTF-8"))?;
    let mut values = Vec::new();

    for line in header_text.split("\r\n").skip(1) {
        let Some((name, value)) = line.split_once(':') else {
            continue;
        };
        if name.eq_ignore_ascii_case("Content-Length") || name.eq_ignore_ascii_case("l") {
            values.push(value.trim().to_string());
        }
    }

    if values.len() != 1 {
        return Err(validation_error(format!(
            "generated SIP message has {} serialized Content-Length headers",
            values.len()
        )));
    }

    let content_length = values[0].parse::<usize>().map_err(|_| {
        validation_error(format!(
            "generated SIP serialized Content-Length is not numeric: {}",
            values[0]
        ))
    })?;

    if content_length != body_len {
        return Err(validation_error(format!(
            "generated SIP serialized Content-Length mismatch: header={}, body={}",
            content_length, body_len
        )));
    }

    Ok(())
}

fn validate_duplicate_singletons(
    headers: &[TypedHeader],
    singleton_headers: &[HeaderName],
    message_kind: &str,
) -> Result<()> {
    let mut counts: HashMap<HeaderName, usize> = HashMap::new();
    for header in headers {
        *counts.entry(header.name()).or_default() += 1;
    }

    for name in singleton_headers {
        if counts.get(name).copied().unwrap_or(0) > 1 {
            return Err(validation_error(format!(
                "generated SIP {} has duplicate singleton {} header",
                message_kind, name
            )));
        }
    }

    Ok(())
}

fn assert_request_semantics_survived(original: &Request, parsed: &Request) -> Result<()> {
    if original.method() != parsed.method() {
        return Err(validation_error(format!(
            "generated request method changed after roundtrip: {} -> {}",
            original.method(),
            parsed.method()
        )));
    }
    if original.uri() != parsed.uri() {
        return Err(validation_error(format!(
            "generated request URI changed after roundtrip: {} -> {}",
            original.uri(),
            parsed.uri()
        )));
    }
    if original.body != parsed.body {
        return Err(validation_error(
            "generated request body changed after roundtrip",
        ));
    }
    assert_core_headers_survived(
        original,
        parsed,
        &[
            HeaderName::Via,
            HeaderName::From,
            HeaderName::To,
            HeaderName::CallId,
            HeaderName::CSeq,
            HeaderName::MaxForwards,
            HeaderName::ContentLength,
        ],
    )
}

fn assert_response_semantics_survived(original: &Response, parsed: &Response) -> Result<()> {
    if original.status_code() != parsed.status_code() {
        return Err(validation_error(format!(
            "generated response status changed after roundtrip: {} -> {}",
            original.status_code(),
            parsed.status_code()
        )));
    }
    if original.body != parsed.body {
        return Err(validation_error(
            "generated response body changed after roundtrip",
        ));
    }
    assert_core_headers_survived(
        original,
        parsed,
        &[
            HeaderName::Via,
            HeaderName::From,
            HeaderName::To,
            HeaderName::CallId,
            HeaderName::CSeq,
            HeaderName::ContentLength,
        ],
    )
}

fn assert_core_headers_survived<M>(original: &M, parsed: &M, headers: &[HeaderName]) -> Result<()>
where
    M: HeaderAccess,
{
    for name in headers {
        if !parsed.has_header(name) {
            return Err(validation_error(format!(
                "generated SIP message lost {} after roundtrip",
                name
            )));
        }

        let original_values = original.raw_headers(name);
        let parsed_values = parsed.raw_headers(name);
        if original_values.len() != parsed_values.len() {
            return Err(validation_error(format!(
                "generated SIP message changed {} count after roundtrip: {} -> {}",
                name,
                original_values.len(),
                parsed_values.len()
            )));
        }
    }

    Ok(())
}
