//! Analyze the WAV files generated by the Asterisk TLS/SRTP DTMF example.

#[path = "../common.rs"]
mod common;

use common::{
    assert_audio_path, endpoint_config, init_tracing, load_env, print_analysis, ExampleResult,
    ENDPOINT_1001_TONE_HZ, ENDPOINT_1002_TONE_HZ,
};

fn main() -> ExampleResult<()> {
    load_env();
    init_tracing();

    let cfg = endpoint_config("1001", 5070, 16000, 16100)?;
    let endpoint_1001_wav = cfg.output_dir.join("tls_srtp_dtmf_1001_received.wav");
    let endpoint_1002_wav = cfg.output_dir.join("tls_srtp_dtmf_1002_received.wav");

    let endpoint_1001 = assert_audio_path(
        &endpoint_1001_wav,
        ENDPOINT_1002_TONE_HZ,
        ENDPOINT_1001_TONE_HZ,
    )?;
    let endpoint_1002 = assert_audio_path(
        &endpoint_1002_wav,
        ENDPOINT_1001_TONE_HZ,
        ENDPOINT_1002_TONE_HZ,
    )?;

    println!("=== Asterisk TLS/SRTP DTMF audio analysis ===");
    print_analysis(
        "1001 received 1002 reference tone",
        &endpoint_1001_wav,
        &endpoint_1001,
    );
    print_analysis(
        "1002 received 1001 reference tone",
        &endpoint_1002_wav,
        &endpoint_1002,
    );
    println!("TLS/SRTP DTMF audio path verification passed.");

    Ok(())
}
