[package]
name = "rvoip-builder"
version = "0.1.0"
edition = "2021"
description = "Flexible composition and configuration patterns for advanced RVOIP deployments"
authors = ["RVOIP Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rvoip/rvoip"
keywords = ["voip", "sip", "rtp", "builder", "composition"]
categories = ["network-programming", "multimedia", "development-tools"]

[dependencies]
# High-level RVOIP crates
rvoip-simple = { path = "../rvoip-simple", version = "0.1.0" }
rvoip-presets = { path = "../rvoip-presets", version = "0.1.0" }

# Core RVOIP crates (for advanced configurations)
rvoip-sip-core = { path = "../sip-core", version = "0.1.0" }
rvoip-sip-client = { path = "../sip-client", version = "0.1.0" }
rvoip-call-engine = { path = "../call-engine", version = "0.1.0" }
rvoip-rtp-core = { path = "../rtp-core", version = "0.1.0" }
rvoip-ice-core = { path = "../ice-core", version = "0.1.0" }
rvoip-media-core = { path = "../media-core", version = "0.1.0" }
rvoip-api-server = { path = "../api-server", version = "0.1.0" }
rvoip-session-core = { path = "../session-core", version = "0.1.0" }
rvoip-transaction-core = { path = "../transaction-core", version = "0.1.0" }
rvoip-infra-common = { path = "../infra-common", version = "0.1.0" }

# Async runtime and utilities
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "sync", "net", "time", "macros"] }
tracing = "0.1.40"
thiserror = "1.0.56"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
uuid = { version = "1.6.1", features = ["v4"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tokio-test = "0.4"
tracing-subscriber = "0.3"

[features]
default = ["full-stack"]
full-stack = ["sip-stack", "rtp-stack", "ice-stack", "media-stack"]
sip-stack = []
rtp-stack = []
ice-stack = []
media-stack = []

# Configuration format support
yaml-config = ["serde_yaml"]
json-config = ["serde_json"]

[[example]]
name = "custom_pbx_builder"
path = "examples/custom_pbx_builder.rs"

[[example]]
name = "microservice_composition"
path = "examples/microservice_composition.rs"

[[example]]
name = "config_driven_deployment"
path = "examples/config_driven_deployment.rs" 