[package]
name = "codec-core"
version = "0.1.0"
edition = "2021"
authors = ["RVoIP Contributors"]
description = "Audio codec implementations for RVoIP"
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-org/rvoip"

[lib]
name = "codec_core"
path = "src/lib.rs"

[[bin]]
name = "g729a_compliance"
path = "src/codecs/g729a/run_compliance_tests.rs"
required-features = []

[lints]
workspace = true

[dependencies]
# Core dependencies
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
bytes = "1.5"

# Performance optimizations
once_cell = "1.19"           # Lazy static initialization for lookup tables
bytemuck = "1.0"             # Safe transmutation between types
rayon = "1.7"                # Parallel processing

# Signal processing
rustfft = "6.1"              # Fast Fourier transforms
num-complex = "0.4"          # Complex number support
apodize = "1.0"              # Windowing functions

# External codec libraries (optional)
opus = { version = "0.3", optional = true }
# g729 = { version = "0.3", optional = true }  # Commented out - licensing required



# Testing dependencies
[dev-dependencies]
tokio = { version = "1.35", features = ["full"] }
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.4"             # Property-based testing
rand = "0.8"                 # Random number generation for tests
temp-dir = "0.1"

# Feature flags
[features]
default = ["g711", "g722", "g729-core", "opus-sim"]

# Individual codec features
g711 = []                    # Always available - no external dependencies
g722 = []                    # Always available - no external dependencies
opus = ["dep:opus"]          # Real Opus - requires external library
opus-sim = []                # Opus simulation - no external dependencies

# G.729 codec variants - allows selective compilation of features
# Core G.729 (8 kbit/s, full complexity)
g729-core = []

# G.729 Annex A (8 kbit/s, reduced complexity ~40% faster)
# Enables simplified pitch analysis, adaptive ACELP, and reduced postfiltering
annex-a = ["g729-core"]

# G.729 Annex B (VAD/DTX/CNG extensions for bandwidth efficiency)
# Enables Voice Activity Detection, Discontinuous Transmission, and Comfort Noise Generation
# Can provide ~50% bandwidth savings during silence periods
annex-b = ["g729-core"]

# Convenience feature to enable all G.729 variants
# Includes G.729, G.729A, G.729B, and G.729BA (A+B combined)
all-annexes = ["annex-a", "annex-b"]

# Development feature for comprehensive testing across all variants
dev-all = ["all-annexes"]

# Legacy features (deprecated - use g729-core instead)
g729 = ["g729-core"]         # Real G.729 - now maps to g729-core
g729-sim = ["g729-core"]     # G.729 simulation - now maps to g729-core

# Performance features
simd = []                    # SIMD optimizations
lut = []                     # Pre-computed lookup tables (enabled by default)

# All codecs
all-codecs = ["g711", "g722", "g729", "opus"]
all-sim = ["g711", "g722", "g729-sim", "opus-sim"]

# Benchmarking
bench = []

# Uncomment to enable benchmarks (requires creating benches/codec_benchmarks.rs)
# [[bench]]
# name = "codec_benchmarks"
# harness = false
# required-features = ["bench"] 