[package]
name = "rvoip-sip-transport"
# 🎯 INHERIT VERSION AND METADATA FROM WORKSPACE!
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

# Crate-specific description
description = "Transport layer for SIP - UDP, TCP, TLS support"

# ✨ INHERIT LINTS FROM WORKSPACE
[lints]
workspace = true

[dependencies]
# 🎯 INTERNAL CRATES
rvoip-sip-core.workspace = true

# External dependencies from workspace
tokio.workspace = true
async-trait.workspace = true
thiserror.workspace = true
anyhow.workspace = true
bytes.workspace = true
tracing.workspace = true

# TLS support
tokio-rustls = { version = "0.24", optional = true }
rustls = { version = "0.21", optional = true }
rustls-pemfile = { version = "1.0", optional = true }

# WebSocket support
tokio-tungstenite = { version = "0.19", optional = true }
http = { version = "0.2", optional = true }

# Add futures-util dependency
futures-util = "0.3"

[features]
default = ["udp", "tcp", "tls", "ws"]
udp = []
tls = ["dep:tokio-rustls", "dep:rustls", "dep:rustls-pemfile"]
tcp = []
ws = ["dep:tokio-tungstenite", "dep:http"]

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
tracing-subscriber = { workspace = true } 