[package]
name = "rtp-loopback"
version = "0.1.0"
edition = "2021"
authors = ["RVOIP Team"]
description = "Example of RTP packet loopback using rtp-core"

[dependencies]
rvoip-rtp-core = { path = "../../crates/rtp-core" }
tokio = { version = "1.28", features = ["full"] }
bytes = "1.4"
tracing = "0.1"
tracing-subscriber = "0.3"
clap = { version = "4.3", features = ["derive"] }
anyhow = "1.0" 