[package]
name = "rvoip-sip-message-test"
version = "0.1.0"
edition = "2021"
description = "A test example for SIP message types and transaction state machine using the rvoip stack"
license = "MIT OR Apache-2.0"

[dependencies]
# Core rvoip crates
rvoip-sip-core = { path = "../../crates/sip-core" }
rvoip-sip-transport = { path = "../../crates/sip-transport" }
rvoip-transaction-core = { path = "../../crates/transaction-core" }

# Async runtime
tokio = { version = "1.36", features = ["full"] }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Utilities
bytes = "1.5"
uuid = { version = "1.7", features = ["v4", "serde"] } 