[package]
name = "rvoip-sip-core"
version = "0.1.0"
edition = "2021"
description = "SIP protocol implementation for the rvoip stack"
license = "MIT OR Apache-2.0"

# Silence all Rust warnings
[lints.rust]
warnings = "allow"

# Features
[features]
default = ["sdp"]  # Include sdp in the default features
lenient_parsing = []  # More lenient parsing for torture tests
sdp = []  # Session Description Protocol support

[dependencies]
# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }
# Serialization
serde = { workspace = true, version = "1.0.219", features = ["derive"] }
serde_json = { workspace = true, version = "1.0.128" }
serde_bytes = "0.11"
# Utilities
bytes = { workspace = true, features = ["serde"] }
uuid = { workspace = true, version = "1.7", features = ["v4"] }
base64 = "0.21"
# Parsing
nom = "7.1"
rand = "0.8"
log = "0.4"
# Logging
tracing = { workspace = true }
ordered-float = { version = "4.2.0", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
proptest = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }

# Integration tests configuration
[[test]]
name = "torture_tests"
path = "tests/rfc_compliance/torture_test.rs"
required-features = ["lenient_parsing"]

[[test]]
name = "parser"
path = "tests/parser_tests.rs"

# Register the new example binaries
[[example]]
name = "01_invite_request_typed"
path = "examples/01_basic_parsing/01_invite_request_typed.rs"

[[example]]
name = "02_sip_response"
path = "examples/01_basic_parsing/02_sip_response.rs"

[[example]]
name = "03_multiple_headers"
path = "examples/01_basic_parsing/03_multiple_headers.rs"

[[example]]
name = "04_sdp_builder"
path = "examples/01_basic_parsing/04_sdp_builder.rs"

[[example]]
name = "01_invite_request_query"
path = "examples/01_basic_parsing/01_invite_request_query.rs"

[[example]]
name = "01_invite_request_path"
path = "examples/01_basic_parsing/01_invite_request_path.rs"
