[package]
name = "rvoip-sip-core"
version = "0.1.0"
edition = "2021"
description = "SIP protocol implementation for the rvoip stack"
license = "MIT OR Apache-2.0"

# Silence all Rust warnings
[lints.rust]
warnings = "allow"

[dependencies]
# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }
# Serialization
serde = { workspace = true, version = "1.0.219", features = ["derive"] }
serde_json = { workspace = true, version = "1.0.128" }
serde_bytes = "0.11"
# Utilities
bytes = { workspace = true, features = ["serde"] }
uuid = { workspace = true, version = "1.7", features = ["v4"] }
# Parsing
nom = "7.1.3"
# Logging
tracing = { workspace = true }
ordered-float = { version = "5.0.0", features = ["serde"] }

[dev-dependencies]
proptest = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }

# Integration tests configuration
[[test]]
name = "torture_tests"
path = "tests/rfc_compliance/torture_test.rs"
