[package]
name = "users-core"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true
description = "User management and authentication service for RVoIP"

[dependencies]
# Async runtime
tokio = { workspace = true, features = ["full"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "sqlite", "json", "chrono", "uuid"] }

# Password hashing
argon2 = "0.5"

# JWT
jsonwebtoken = "9.3"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# UUID generation
uuid = { version = "1.11", features = ["v4", "serde"] }

# Date/time
chrono = { version = "0.4", features = ["serde"] }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Async traits
async-trait = "0.1"

# Web framework (for REST API)
axum = { version = "0.7", features = ["http2", "json", "tokio"] }
tower = { version = "0.5", features = ["full"] }
tower-http = { version = "0.6", features = ["cors", "trace"] }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }

# Configuration
config = "0.14"

# Cryptography
rand = "0.8"
base64 = "0.22"
sha2 = "0.10"

# Validation
validator = { version = "0.18", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
tempfile = "3.14"

[lints]
workspace = true
