[package]
name = "audio-streaming-demo"
version = "0.1.0"
edition = "2021"
description = "Real-time audio streaming SIP call demo using microphone and speakers"

[[bin]]
name = "audio_peer"
path = "src/audio_peer.rs"

[dependencies]
rvoip = "0.1.14"

# Audio dependencies
cpal = "0.15"

# Async and utilities
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
anyhow = "1.0"
uuid = { version = "1.0", features = ["v4"] }
async-trait = "0.1"
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }

[workspace] 