[package]
name = "rvoip"
version = "0.1.3"
edition = "2021"
description = "A comprehensive VoIP library for Rust"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rvoip"
homepage = "https://github.com/eisenzopf/rvoip"
repository = "https://github.com/eisenzopf/rvoip"

[dependencies]
# Re-export all the crates in the workspace
rvoip-sip-core = { path = "../sip-core", version = "0.1.2" }
rvoip-sip-transport = { path = "../sip-transport", version = "0.1.2" }
rvoip-transaction-core = { path = "../transaction-core", version = "0.1.2" }
rvoip-dialog-core = { path = "../dialog-core", version = "0.1.2" }
rvoip-rtp-core = { path = "../rtp-core", version = "0.1.2" }
rvoip-media-core = { path = "../media-core", version = "0.1.2" }
rvoip-session-core = { path = "../session-core", version = "0.1.2" }
rvoip-call-engine = { path = "../call-engine", version = "0.1.2" }
rvoip-client-core = { path = "../client-core", version = "0.1.2" } 