[package]
name = "rvoip"
version = "0.1.1"
edition = "2021"
description = "A comprehensive VoIP library for Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-username/rvoip"
authors = ["Your Name <your-email@example.com>"]

[dependencies]
# Re-export all the crates in the workspace
rvoip-sip-core = { path = "../sip-core", version = "0.1.1" }
rvoip-sip-transport = { path = "../sip-transport", version = "0.1.1" }
rvoip-transaction-core = { path = "../transaction-core", version = "0.1.1" }
rvoip-dialog-core = { path = "../dialog-core", version = "0.1.1" }
rvoip-rtp-core = { path = "../rtp-core", version = "0.1.1" }
rvoip-media-core = { path = "../media-core", version = "0.1.1" }
rvoip-session-core = { path = "../session-core", version = "0.1.1" }
rvoip-call-engine = { path = "../call-engine", version = "0.1.1" }
rvoip-client-core = { path = "../client-core", version = "0.1.1" } 