[package]
name = "sip-client-p2p"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
rvoip = "0.1.20"
tokio = { version = "1.0", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
colored = "2.0"
local-ip-address = "0.6"