[package]
name = "rvoip-media-core"
version = "0.1.0"
edition = "2021"
description = "Core media handling functionality for the RVOIP project"

# Silence all Rust warnings
[lints.rust]
warnings = "allow"

[dependencies]
# Use the rtp-core crate from our workspace
rvoip-rtp-core = { path = "../rtp-core" }
rvoip-ice-core = { path = "../ice-core" }

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Error handling
thiserror = "1.0"

# Async runtime
tokio = { version = "1.35", features = ["full"] }

# Bytes handling
bytes = "1.5"

# CLI argument parsing for the demo binary
clap = { version = "4.4", features = ["derive"] }

# Serde for serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Random generation
rand = "0.8"

# Missing dependencies needed for compilation
uuid = { version = "1.0", features = ["v4"] }
bytemuck = "1.0"

# Media codecs (optional)
opus = { version = "0.3", optional = true }
# g729 = { version = "0.3", optional = true }  # Commented out due to missing dependency

[features]
default = ["pcmu", "pcma"]
pcmu = []
pcma = []
g722 = []
# g729 = ["dep:g729"]  # Commented out due to missing dependency
opus = ["dep:opus"]
all-codecs = ["pcmu", "pcma", "g722", "opus"]  # removed g729 due to missing dependency

[dev-dependencies] 