[package]
name = "rvoip-sip-client"
version = "0.2.1"
edition = "2021"
description = "High-level SIP client library for the RVOIP SIP stack - Recently restructured for better maintainability"
authors = ["rvoip team"]
repository = "https://github.com/rudeless/rvoip"
license = "MIT"

# Turn off specific warnings
[lints.rust]
unused_imports = "allow"
warnings = "allow"  # Ignore all warnings

[dependencies]
# Core crates
rvoip-sip-core = { path = "../sip-core" }
rvoip-sip-transport = { path = "../sip-transport", features = ["tls"] }
rvoip-transaction-core = { path = "../transaction-core" }
rvoip-session-core = { path = "../session-core" }
rvoip-rtp-core = { path = "../rtp-core" }
rvoip-media-core = { path = "../media-core" }
rvoip-call-engine = { path = "../call-engine" }
rvoip-ice-core = { path = "../ice-core" }

# Async runtime and utilities
tokio = { version = "1.29", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
uuid = { version = "1.4", features = ["v4"] }
async-trait = "0.1"
bytes = "1.4"
md5 = "0.7"
futures = "0.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13"

# NAT traversal and secure transport
webrtc-ice = "0.10"  # ICE protocol implementation
tokio-rustls = "0.24"  # TLS support for tokio
rustls = "0.21"  # TLS implementation
webrtc-dtls = "0.8"  # DTLS for media security
webrtc-srtp = "0.10"  # SRTP for encrypted media
stun = "0.4"  # STUN protocol support
turn = "0.6"  # TURN protocol support

# Additional media codecs
opus = { version = "0.3", optional = true }  # Opus codec
# g729 = { version = "0.3", optional = true }  # G.729 codec - Commented out due to missing dependency

[features]
default = ["ice"]
pcmu = ["rvoip-media-core/pcmu"]
pcma = ["rvoip-media-core/pcma"]
g722 = ["rvoip-media-core/g722"]
# g729 = ["rvoip-media-core/g729", "dep:g729"]  # Commented out due to missing dependency
opus = ["rvoip-media-core/opus", "dep:opus"]
all-codecs = ["pcmu", "pcma", "g722", "opus"] # removed g729 due to missing dependency
ice = []

[dev-dependencies]
tracing-subscriber = "0.3"
clap = { version = "4.3", features = ["derive"] } 