[package]
name = "rvoip-sip-client"
# 🎯 INHERIT VERSION AND METADATA FROM WORKSPACE!
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

# Crate-specific description
description = "Unified SIP client library orchestrating client-core, audio-core, and codec-core for production-ready VoIP applications"

# ✨ INHERIT LINTS FROM WORKSPACE
[lints]
workspace = true

[dependencies]
# Core rvoip dependencies
rvoip-client-core = { path = "../client-core", version = "0.1.4" }
rvoip-audio-core = { path = "../audio-core", version = "0.1.4" }
rvoip-codec-core = { path = "../codec-core", version = "0.1.4" }

# Session core for types
rvoip-session-core = { path = "../session-core", version = "0.1.4" }

# Async runtime and utilities
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
futures = "0.3"
tokio-stream = { version = "0.1", features = ["sync"] }

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging and tracing
tracing = "0.1"

# Data structures
dashmap = "5.5"
parking_lot = "0.12"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Time handling
chrono = "0.4"

[dev-dependencies]
# Testing utilities
tokio-test = "0.4"
tracing-test = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Mock and test utilities
mockall = "0.12"
serial_test = "3.1"

[features]
default = ["simple-api", "advanced-api", "audio-processing"]

# API features
simple-api = []
advanced-api = []

# Audio features
audio-processing = ["rvoip-audio-core/processing-all"]
custom-audio = ["rvoip-audio-core/device-mock"]

# Codec features
all-codecs = ["rvoip-codec-core/g711"]
g711-only = ["rvoip-codec-core/g711"]

# Development features
mock-audio = ["rvoip-audio-core/device-mock"]
examples = []

# Examples will be added in later phases