[package]
name = "rvoip-sip-client"
# 🎯 INHERIT VERSION AND METADATA FROM WORKSPACE!
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true

# Crate-specific description
description = "Unified SIP client library orchestrating client-core, audio-core, and codec-core for production-ready VoIP applications"

# ✨ INHERIT LINTS FROM WORKSPACE
[lints]
workspace = true

[dependencies]
# 🎯 INTERNAL CRATES - Use workspace dependencies (no version needed!)
rvoip-client-core.workspace = true
rvoip-audio-core.workspace = true
rvoip-codec-core.workspace = true
rvoip-session-core.workspace = true

# External dependencies from workspace
tokio.workspace = true
async-trait.workspace = true
futures.workspace = true
tokio-stream.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
dashmap.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true

[dev-dependencies]
tokio.workspace = true
tracing-subscriber.workspace = true

# Crate-specific dev dependencies that aren't in workspace
tokio-test = "0.4"
tracing-test = "0.2"
mockall = "0.12"
serial_test = "3.1"

[features]
default = ["simple-api", "advanced-api", "audio-processing"]

# API features
simple-api = []
advanced-api = []

# Audio features
audio-processing = ["rvoip-audio-core/processing-all"]
custom-audio = ["rvoip-audio-core/device-mock"]

# Codec features
all-codecs = ["rvoip-codec-core/g711"]
g711-only = ["rvoip-codec-core/g711"]

# Development features
mock-audio = ["rvoip-audio-core/device-mock"]
examples = []

# Examples will be added in later phases