[package]
name = "rvoip-sip-client"
version = "0.3.0"
edition = "2021"
description = "Simple, clean SIP client library and CLI tool for the RVOIP stack"
authors = ["rvoip team"]
repository = "https://github.com/rudeless/rvoip"
license = "MIT"

# Silence all Rust warnings during development
[lints.rust]
warnings = "allow"

[[bin]]
name = "rvoip-sip-client"
path = "src/cli/main.rs"

[dependencies]
# Core RVOIP infrastructure
rvoip-client-core = { path = "../client-core" }

# Essential async runtime and utilities
tokio = { version = "1.29", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"

# Serialization and configuration
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
uuid = { version = "1.4", features = ["v4"] }

# CLI support
clap = { version = "4.3", features = ["derive"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Async utilities
futures = "0.3"
async-trait = "0.1"

[dev-dependencies]
# Testing utilities
test-log = "0.2"

[features]
default = []
# Future features for specific codec support can be added here
# These would pass through to client-core/media-core
# pcmu = ["rvoip-client-core/pcmu"]
# pcma = ["rvoip-client-core/pcma"] 