//! Analyze the WAV files generated by the Asterisk hold/resume example.

#[path = "../common.rs"]
mod common;

use common::{
    analyze_samples, assert_audio_path, endpoint_config, init_tracing, load_env, print_analysis,
    read_wav, ExampleResult, ENDPOINT_2001_TONE_HZ, ENDPOINT_2002_TONE_HZ, SAMPLE_RATE,
};

const PRE_HOLD_TONE_HZ: f32 = ENDPOINT_2001_TONE_HZ;
const DURING_HOLD_TONE_HZ: f32 = 550.0;
const POST_RESUME_TONE_HZ: f32 = 660.0;
const WINDOW_SAMPLES: usize = SAMPLE_RATE as usize;
const MIN_CALLER_SAMPLES: usize = WINDOW_SAMPLES * 2;

fn main() -> ExampleResult<()> {
    load_env();
    init_tracing();

    let cfg = endpoint_config("2001", 5080, 17000, 17100)?;
    let endpoint_2001_wav = cfg.output_dir.join("hold_resume_2001_received.wav");
    let endpoint_2002_wav = cfg.output_dir.join("hold_resume_2002_received.wav");

    let endpoint_2001 = assert_audio_path(
        &endpoint_2001_wav,
        ENDPOINT_2002_TONE_HZ,
        ENDPOINT_2001_TONE_HZ,
    )?;

    let endpoint_2002_samples = read_wav(&endpoint_2002_wav)?;
    if endpoint_2002_samples.len() < MIN_CALLER_SAMPLES {
        return Err(format!(
            "{} too short: {} samples (expected at least {})",
            endpoint_2002_wav.display(),
            endpoint_2002_samples.len(),
            MIN_CALLER_SAMPLES
        )
        .into());
    }

    let first_window = &endpoint_2002_samples[..WINDOW_SAMPLES];
    let last_window = &endpoint_2002_samples[endpoint_2002_samples.len() - WINDOW_SAMPLES..];
    let pre_hold = assert_window_tone(
        "2002 pre-hold window",
        first_window,
        PRE_HOLD_TONE_HZ,
        POST_RESUME_TONE_HZ,
    )?;
    let post_resume = assert_window_tone(
        "2002 post-resume window",
        last_window,
        POST_RESUME_TONE_HZ,
        PRE_HOLD_TONE_HZ,
    )?;
    let during_hold_probe = analyze_samples(
        &endpoint_2002_samples,
        DURING_HOLD_TONE_HZ,
        PRE_HOLD_TONE_HZ,
    )?;

    println!("=== Asterisk hold/resume audio analysis ===");
    print_analysis(
        "2001 received 2002 reference tone",
        &endpoint_2001_wav,
        &endpoint_2001,
    );
    print_analysis("2002 pre-hold caller tone", &endpoint_2002_wav, &pre_hold);
    print_analysis(
        "2002 post-resume caller tone",
        &endpoint_2002_wav,
        &post_resume,
    );
    println!(
        "2002 during-hold {:.0}Hz probe magnitude {:.1} (informational; exact hold media behavior is PBX-dependent)",
        DURING_HOLD_TONE_HZ, during_hold_probe.expected_magnitude
    );
    println!("Hold/resume audio path verification passed.");

    Ok(())
}

fn assert_window_tone(
    label: &str,
    samples: &[i16],
    expected_hz: f32,
    rejected_hz: f32,
) -> ExampleResult<common::ToneAnalysis> {
    let analysis = analyze_samples(samples, expected_hz, rejected_hz)?;
    if analysis.ratio < common::DOMINANCE_RATIO {
        return Err(format!(
            "{}: {:.0}Hz magnitude {:.1} vs {:.0}Hz magnitude {:.1}, ratio {:.2} (expected at least {:.2})",
            label,
            analysis.expected_hz,
            analysis.expected_magnitude,
            analysis.rejected_hz,
            analysis.rejected_magnitude,
            analysis.ratio,
            common::DOMINANCE_RATIO
        )
        .into());
    }
    Ok(analysis)
}
