[package]
name = "rvoip-client-core"
version = "0.1.0"
edition = "2021"
description = "SIP client coordination layer - leverages rvoip infrastructure for client applications"
license = "MIT OR Apache-2.0"
repository = "https://github.com/your-org/rvoip"
keywords = ["sip", "voip", "client", "telecommunications", "rtp"]
categories = ["network-programming", "multimedia"]

[dependencies]
# Core rvoip infrastructure (PROPER LAYER SEPARATION!)
# session-core handles ALL lower-level integration
rvoip-session-core = { path = "../session-core" }

# No direct access to lower layers - session-core handles ALL of these:
# rvoip-transaction-core, rvoip-sip-core, rvoip-sip-transport, 
# rvoip-media-core, rvoip-rtp-core, rvoip-dialog-core
infra-common = { path = "../infra-common" }

# Async runtime and utilities
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
futures = "0.3"

# Data structures and utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
dashmap = "5.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Networking and time
url = "2.5"
chrono = { version = "0.4", features = ["serde"] }

# Logging and error handling
tracing = "0.1"
anyhow = "1.0"
thiserror = "1.0"

# Random number generation for jitter
rand = "0.8"

[dev-dependencies]
tokio-test = "0.4"
tracing-test = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serial_test = "3.1"

[features]
default = []
# Enable audio device integration (future)
audio-devices = []
# Enable video support (future)  
video = []
# Enable advanced codecs (future)
advanced-codecs = []

# Example configurations
[[example]]
name = "sipp_integration_sip_test_server"
path = "examples/sipp_integration/sip_test_server.rs" 