#!/usr/bin/env python3
"""Emit the AMR-WB gain quantiser and math tables as Rust from TS 26.173."""
import re
import sys

src_dir, out_path = sys.argv[1], sys.argv[2]


def array(path, name, count):
    raw = open(f"{src_dir}/{path}").read()
    body = raw.split(f"{name}[", 1)[1].split("{", 1)[1].split("}", 1)[0]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    vals = [int(x) for x in re.findall(r"-?\d+", body)]
    assert len(vals) == count, f"{name}: got {len(vals)}, want {count}"
    return vals


TABLES = [
    ("q_gain2.tab", "t_qua_gain6b", "QUA_GAIN_6B", 128, 2,
     "Gain codebook for the 6-bit modes.\n"
     "///\n"
     "/// 64 entries of (pitch gain Q14, code gain Q11). The two are quantised\n"
     "/// jointly because they are strongly correlated -- a voiced frame wants\n"
     "/// high pitch gain and low code gain, and coding them independently\n"
     "/// would waste bits on combinations that never occur."),
    ("q_gain2.tab", "t_qua_gain7b", "QUA_GAIN_7B", 256, 2,
     "Gain codebook for the 7-bit modes: 128 entries of (pitch gain Q14, code\n"
     "/// gain Q11)."),
    ("math_op.c", "table_isqrt", "ISQRT_TABLE", 49, 10,
     "`1/sqrt(x)` sampled at 49 points, Q15, with linear interpolation between."),
    ("math_op.c", "table_pow2", "POW2_TABLE", 33, 10,
     "`2^x` over one octave, sampled at 33 points, Q15."),
    ("log2_tab.h", "table", "LOG2_TABLE", 33, 10,
     "`log2(x)` over one octave, sampled at 33 points, Q15."),
]

HEADER = '''//! Gain quantiser and math tables for AMR-WB, from the TS 26.173 reference.
//!
//! The math tables are AMR-WB's own. G.729 has tables for the same functions
//! with different values, and mixing them would give a codec that sounds
//! nearly right and fails conformance -- which is why these live here rather
//! than in the shared `fixed_point` module.
//!
//! Generated by `tools/gen_gain_tables.py`.

'''

parts = []
for path, c_name, rust_name, count, per_line, doc in TABLES:
    vals = array(path, c_name, count)
    lines = [f"/// {doc}", f"pub const {rust_name}: [i16; {count}] = ["]
    for i in range(0, count, per_line):
        lines.append("    " + ", ".join(str(v) for v in vals[i : i + per_line]) + ",")
    lines.append("];")
    parts.append("\n".join(lines))

with open(out_path, "w") as f:
    f.write(HEADER)
    f.write("\n\n".join(parts) + "\n")

print(f"wrote {out_path}: {len(TABLES)} tables")
