//! Analyze the WAV files generated by the Asterisk TLS/SRTP hold/resume example.

#[path = "../common.rs"]
mod common;

use common::{
    analyze_samples, assert_audio_path, assert_samples_tone, endpoint_config, init_tracing,
    load_env, print_analysis, read_wav, ExampleResult, ENDPOINT_1001_TONE_HZ,
    ENDPOINT_1002_TONE_HZ, SAMPLE_RATE,
};

const PRE_HOLD_TONE_HZ: f32 = ENDPOINT_1001_TONE_HZ;
const DURING_HOLD_TONE_HZ: f32 = 550.0;
const POST_RESUME_TONE_HZ: f32 = 660.0;
const WINDOW_SAMPLES: usize = SAMPLE_RATE as usize;
const MIN_CALLER_SAMPLES: usize = WINDOW_SAMPLES * 2;

fn main() -> ExampleResult<()> {
    load_env();
    init_tracing();

    let cfg = endpoint_config("1001", 5070, 16000, 16100)?;
    let endpoint_1001_wav = cfg
        .output_dir
        .join("tls_srtp_hold_resume_1001_received.wav");
    let endpoint_1002_wav = cfg
        .output_dir
        .join("tls_srtp_hold_resume_1002_received.wav");

    let endpoint_1001 = assert_audio_path(
        &endpoint_1001_wav,
        ENDPOINT_1002_TONE_HZ,
        ENDPOINT_1001_TONE_HZ,
    )?;

    let endpoint_1002_samples = read_wav(&endpoint_1002_wav)?;
    if endpoint_1002_samples.len() < MIN_CALLER_SAMPLES {
        return Err(format!(
            "{} too short: {} samples (expected at least {})",
            endpoint_1002_wav.display(),
            endpoint_1002_samples.len(),
            MIN_CALLER_SAMPLES
        )
        .into());
    }

    let first_window = &endpoint_1002_samples[..WINDOW_SAMPLES];
    let last_window = &endpoint_1002_samples[endpoint_1002_samples.len() - WINDOW_SAMPLES..];
    let pre_hold = assert_samples_tone(
        "1002 pre-hold TLS/SRTP caller tone",
        first_window,
        PRE_HOLD_TONE_HZ,
        POST_RESUME_TONE_HZ,
    )?;
    let post_resume = assert_samples_tone(
        "1002 post-resume TLS/SRTP caller tone",
        last_window,
        POST_RESUME_TONE_HZ,
        PRE_HOLD_TONE_HZ,
    )?;
    let during_hold_probe = analyze_samples(
        &endpoint_1002_samples,
        DURING_HOLD_TONE_HZ,
        PRE_HOLD_TONE_HZ,
    )?;

    println!("=== Asterisk TLS/SRTP hold/resume audio analysis ===");
    print_analysis(
        "1001 received 1002 reference tone",
        &endpoint_1001_wav,
        &endpoint_1001,
    );
    print_analysis("1002 pre-hold caller tone", &endpoint_1002_wav, &pre_hold);
    print_analysis(
        "1002 post-resume caller tone",
        &endpoint_1002_wav,
        &post_resume,
    );
    println!(
        "1002 during-hold {:.0}Hz probe magnitude {:.1} (informational; exact hold media behavior is PBX-dependent)",
        DURING_HOLD_TONE_HZ, during_hold_probe.expected_magnitude
    );
    println!("TLS/SRTP hold/resume audio path verification passed.");

    Ok(())
}
