[package]
name = "simple-session"
version = "0.1.0"
edition = "2021"

[dependencies]
# RVOIP crates
rvoip-sip-core = { path = "../../crates/sip-core" }
rvoip-sip-transport = { path = "../../crates/sip-transport" }
rvoip-transaction-core = { path = "../../crates/transaction-core" }
rvoip-rtp-core = { path = "../../crates/rtp-core" }
rvoip-media-core = { path = "../../crates/media-core" }
rvoip-session-core = { path = "../../crates/session-core" }

# Async runtime
tokio = { version = "1.36", features = ["full"] }

# Error handling
anyhow = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Command line
clap = { version = "4.5", features = ["derive"] }

# Utilities
uuid = { version = "1.4", features = ["v4"] } 