# -----------------------------------------------------------------------------
# makefile for compiling and testing the G.722 Appendix IV
# "A low-complexity algorithm for packet loss concealment with G.722"
# Version:       1.1
# Revision Date: Jul 3, 2007 
# -----------------------------------------------------------------------------

# ------------------------------------------------
# Choose compiler and set options 
# ------------------------------------------------
CC = gcc
CFLAGS = -Wall -fno-builtin -I../src/stl2005_basop -I../src #-pedantic -std=c99
LD_FLAGS =

# ------------------------------------
#  Lists of object files
# ------------------------------------

G722DEC_OBJ = \
../src/decg722.o\
../src/funcg722.o \
../src/g722.o \
../src/g722_plc.o \
../src/g722_plc_tables.o \
../src/oper_32b.o \
../src/softbit.o \
../src/stl2005_basop/basop32.o \
../src/stl2005_basop/control.o \
../src/stl2005_basop/count.o \
../src/stl2005_basop/enh1632.o

# ------------------------------------
# Targets 
# ------------------------------------
all: decg722

clean:
	@ rm -f `find .. -name '*~'` `find ..  -name '*.o'`

bigclean: clean
	$(RM) decg722*

decg722: $(G722DEC_OBJ)
	$(CC) $(CC_OPT) -o $@ $^ $(LD_OPT) -lm


