[package]
name = "rvoip-simple"
version = "0.1.0"
edition = "2021"
description = "Simple, developer-friendly VoIP client APIs built on RVOIP"
authors = ["RVOIP Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rvoip/rvoip"
keywords = ["voip", "sip", "rtp", "webrtc", "communication"]
categories = ["network-programming", "multimedia", "api-bindings"]

[dependencies]
# Core RVOIP crates
rvoip-sip-core = { path = "../sip-core", version = "0.1.0" }
rvoip-sip-client = { path = "../sip-client", version = "0.1.0" }
rvoip-rtp-core = { path = "../rtp-core", version = "0.1.0" }
rvoip-ice-core = { path = "../ice-core", version = "0.1.0" }
rvoip-media-core = { path = "../media-core", version = "0.1.0" }
rvoip-infra-common = { path = "../infra-common", version = "0.1.0" }

# Async runtime and utilities
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "sync", "net", "time", "macros"] }
tracing = "0.1.40"
thiserror = "1.0.56"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.6.1", features = ["v4"] }
async-trait = "0.1"

[dev-dependencies]
tokio-test = "0.4"
tracing-subscriber = "0.3"

[features]
default = ["simple-client"]
simple-client = []
p2p-calling = []
pstn-gateway = []

[[example]]
name = "simple_voip_client"
path = "examples/simple_voip_client.rs"

[[example]]
name = "p2p_secure_call"
path = "examples/p2p_secure_call.rs" 