!interesting-Method0123456789_*+`.%indeed'~ sip:1_unusual.URI~(to-be!sure)&isn't+it$/crazy?,/;;* :&it+has=1,weird!*pas$wo~d_too.(doesn't-it) @example.com SIP/2.0
Via: SIP/2.0/TCP host1.example.com;branch=z9hG4bK-.!%66*_+`'~
To: "BEL:\x07 NUL:\x00 DEL:\x7F" <sip:1_unusual.URI~(to-be!sure)&isn't+it$/crazy?,/;;* @example.com>
From: token1~` token2'+_ token3*%!.- <sip:mundane@example.com> ;fromParam''~+*_!.-%="работающий" ;tag=_token~1'+`*%!-. 
Call-ID: intmeth.word%ZK-!.*_+'@word`~)(><:\/"\\[?}{}
CSeq: 139122385 !interesting-Method0123456789_*+`.%indeed'~
Max-Forwards: 255
extensionHeader-!.%*+_`'~: ￿大停電
Content-Length: 0 