[package]
name = "dialog-test"
version = "0.1.0"
edition = "2021"

[dependencies]
rvoip-session-core = { path = "../crates/session-core" }
rvoip-sip-core = { path = "../crates/sip-core" }
tokio = { version = "1.0", features = ["full"] } 