[package]
name = "rtp-core"
version = "0.1.0"
edition = "2021"
description = "RTP packet encoding/decoding, RTCP support for rvoip"
authors = ["RVOIP Team"]

[dependencies]
bytes = "1.4"
thiserror = "1.0"
tokio = { version = "1.28", features = ["full"] }
tracing = "0.1"
bitvec = "1.0"
rand = "0.8"

[dev-dependencies]
tokio-test = "0.4" 