[package]
name = "rvoip-rtp-core"
version = "0.1.0"
edition = "2021"
description = "RTP packet encoding/decoding, RTCP support for rvoip"
authors = ["RVOIP Team"]

# Silence all Rust warnings
[lints.rust]
warnings = "allow"

[dependencies]
bytes = "1.5"
thiserror = "1.0"
tokio = { version = "1.21", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
bitvec = "1.0"
rand = "0.8"
async-trait = "0.1"
base64 = "0.13"

[dev-dependencies]
tokio-test = "0.4" 