[package]
name = "rvoip-rtp-core"
version = "0.1.0"
edition = "2021"
description = "RTP packet encoding/decoding, RTCP support for rvoip"
authors = ["RVOIP Team"]

# Silence all Rust warnings
[lints.rust]
warnings = "allow"

[dependencies]
bytes = "1.5.0"
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "sync", "net", "time", "macros", "full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3"
bitvec = "1.0"
rand = "0.8.5"
async-trait = "0.1"
base64 = "0.13"
log = "0.4"
futures = "0.3.30"
# Cryptographic dependencies for DTLS
hmac = "0.12.1"
sha1 = "0.10"
sha2 = "0.10.8"
aes = "0.8"
ctr = "0.9"
aes-gcm = "0.10.3"
p256 = { version = "0.13.2", features = ["ecdh"] }
x509-parser = "0.15.1"
rcgen = "0.11.3"
webrtc-dtls = "0.9.0"
rsa = "0.9.6"
ring = "0.17"
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rustls-pemfile = "1.0.4"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.6.1", features = ["v4"] }
either = "1.9.0"
nix = { version = "0.27.1", features = ["socket"] }
libc = "0.2"
winapi = { version = "0.3", features = ["winsock2", "ws2def"] }

[dev-dependencies]
tokio-test = "0.4"

[[example]]
name = "dtls_test"
path = "examples/dtls_test.rs" 