[book]
title = "SIP Core Interactive Tutorial"
authors = ["Rudeless Ventures"]
description = "An interactive tutorial for building and parsing SIP/SDP messages using the rvoip-sip-core library"
src = "src"
language = "en"

[output.html]
mathjax-support = false
git-repository-url = "https://github.com/rudeless/rvoip"
edit-url-template = "https://github.com/rudeless/rvoip/edit/main/crates/sip-core/examples/tutorial/{path}"
additional-css = ["custom.css"]
additional-js = ["custom.js"]

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
enable = true
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2 